continue work on elaboration

diff --git a/test2/mkfile b/test2/mkfile
--- a/test2/mkfile
+++ b/test2/mkfile
@@ -39,8 +39,8 @@ testdrv.lua:D:  testdrv.nw
 	$QC testdrv.lua $target
 
 tiger.tst:QV:
-	if [ -x ../../frontends/tiger/tigerc ]; then
+	if ../../frontends/tiger/tigerc 2>/dev/null; then
 	  $QC testdrv.lua tiger.tst
 	else
-	  : no harm, no foul
+	  echo "# Cannot execute Tiger compiler" 1>&2
 	fi
